name: flutter_loja_virtual
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_staggered_grid_view: ^0.2.7
  cloud_firestore: ^0.8.2+3
  carousel_pro: ^0.0.13
  transparent_image: 0.1.0
  scoped_model: ^1.0.1
  path_provider: ^0.5.0+1
  firebase_auth: ^0.7.0
  url_launcher: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true